export enum PageRoutes {
  Dashboard = '/internal/dashboard',
  NewProduct = '/internal/supply/new',
  ListProducts = '/internal/supply',
  NewProperty = '/internal/properties/new',
  ListProperties = '/internal/properties',
  NewPlot = '/internal/plots/new',
  ListPlots = '/internal/plots',
  NewOperations = '/internal/operations/new',
  ListOperations = '/internal/operations',
  NewPurchases = '/internal/purchases/new',
  ListPurchases = '/internal/purchases',
  NewProductivity = '/internal/productivity/new',
  ListProductivity = '/internal/productivity',
  Login = '/login',
}
